spring:
  redis:
    host: 139.196.218.1
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
      restart:
        # 默认为true
        enabled: true

    restart:
      # 默认为true
      enabled: true
  rabbitmq:
    host: 139.196.218.1
    username: bwx
    password: bwx
