spring:
  redis:
    host: 115.120.240.44
    port: 6379
    password: bi517828158
  datasource:
    url: jdbc:mysql://115.120.240.44:3306/YUNDOC?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
      restart:
        # 默认为true
        enabled: true

  rabbitmq:
    host: 115.120.240.44
    username: admin
    password: admin
    port: 5672

