person:
  age: 3
  happy: false
  birth: 2000/01/01
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - girl
    - music
  user:
    name: 旺财
    age: 1
  name: jier

spring:
  redis:
    host: 127.0.0.1
    port: 6379